// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialHX.Data;

#nullable disable

namespace SocialHX.Migrations
{
    [DbContext(typeof(SocialHXContext))]
    [Migration("20260915234930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SocialHX.Models.Activity", b =>
                {
                    b.Property<int>("Event_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Event_ID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("SocialHX.Models.Follow_Up", b =>
                {
                    b.Property<int>("Follow_Up_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Case_Number")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Response")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Student_Adjustments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Student_Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Follow_Up_ID");

                    b.ToTable("Follow_Up");
                });

            modelBuilder.Entity("SocialHX.Models.Prescribed_Event", b =>
                {
                    b.Property<int>("Prescribed_Event_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Other_Person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Prescribed_Event_ID");

                    b.ToTable("Prescribed_Event");
                });

            modelBuilder.Entity("SocialHX.Models.Prescriber", b =>
                {
                    b.Property<int>("Prescriber_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Prescriber_ID");

                    b.ToTable("Prescriber");
                });

            modelBuilder.Entity("SocialHX.Models.Prescription", b =>
                {
                    b.Property<int>("Case_Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Event1_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event2_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event3_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event4_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Follow_Up_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Follow_Up_Refill_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prescriber_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Student_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Case_Number");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("SocialHX.Models.Student", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Student_ID");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
